TRUNCATE noteful_notes RESTART IDENTITY CASCADE;

INSERT INTO noteful_notes
    (note_name, folder_id, content)
VALUES
    ('Dogs', 1, 'Eum qui odit in exercitationem excepturi. Qui occaecati totam reprehenderit libero. Qui corporis sint voluptatum. Quod aut omnis rem temporibus quia officiis veritatis unde. Velit natus sed esse magni quod dignissimos corporis magnam et. Adipisci dolor omnis doloribus dolorem et ad et.\n \rQuidem non ad minus possimus vel quisquam occaecati. Ducimus repellat consequuntur omnis quasi vel et in. Et omnis architecto ut sit illum. Placeat deserunt eligendi. Accusamus labore dignissimos libero est magni dolor nostrum. Iusto non modi aut vitae est non.\n \rVel sint adipisci. Iure error debitis et et quaerat earum. Tempora qui rerum. Ut cumque est aliquam. Ad assumenda reiciendis dolorem et ad et corrupti. Veritatis et rerum aliquam rerum numquam vero nihil cupiditate.'),
    ('Cats', 2, 'Expedita natus maxime est deleniti consectetur aut voluptatem nisi. Veritatis id enim asperiores. In error tempore occaecati itaque quis. Nam sequi quos et natus vitae quasi natus quod deleniti.\n \rAlias officia quis similique pariatur placeat unde nihil ut. Quia asperiores sed libero dolorum id. Debitis amet assumenda impedit eos vel non ratione.\n \rEnim aut quasi iure delectus quia consectetur quisquam unde facilis. Voluptatem quia nihil delectus est nam quidem alias. Sint nesciunt laudantium non labore qui neque ut nobis. Nemo eius non occaecati eum omnis molestiae. Velit ex nobis assumenda dicta. Veritatis quibusdam soluta.'),
    ('Pigs', 3, 'Laudantium rerum sit minus dolor eum. Quae rem incidunt ea tempora sit labore reiciendis veniam. Dolore commodi itaque.\n \rQuibusdam expedita dolorem amet eos sint ab rerum. Qui itaque perspiciatis molestiae in. Facere qui in illo voluptas nihil et debitis. Omnis architecto autem.\n \rTemporibus illum molestiae consequatur explicabo omnis debitis magnam. Iure ab sed beatae inventore. Deleniti voluptate repellat consectetur ut possimus qui tempora. Vitae eveniet numquam dolorem. In porro neque assumenda accusamus in minima asperiores dolores. Cum et nulla.'),
    ('Birds', 1, 'Vel commodi sed est fugiat temporibus. Quaerat aut quo ullam. Quo assumenda tempore voluptas facilis distinctio maiores cumque.\n \rMagnam aut animi. Ducimus rem quia maxime. Voluptas consequatur minima dolorem ut omnis porro culpa officiis quibusdam. Asperiores blanditiis nam unde velit repudiandae ut nesciunt.\n \rSimilique facere hic architecto sit qui. Tempore repellat animi quam quia eos molestiae et eum ducimus. Autem et quae facilis rem repudiandae.'),
    ('Bears', 2, 'Cupiditate laudantium vitae maxime voluptas ratione. Beatae eos delectus deserunt et. Reprehenderit vero quis itaque in consequuntur voluptate. Qui dignissimos vitae. Magnam eum ipsam voluptatem qui sequi sunt possimus quo. Nostrum dolor id aut ea non dolorem nisi aut.\n \rUt provident nihil et enim totam sunt ea laboriosam. Velit esse cumque alias aliquam enim delectus. Fuga non dicta beatae. Quaerat maxime dolorum animi nisi atque amet odio ut.\n \rVoluptatibus facere placeat molestiae error perspiciatis provident magnam. Quibusdam labore maxime illum. Hic vel in. Assumenda aspernatur aliquid consequatur distinctio numquam.'),
    ('Horses', 3, 'Sequi commodi ab consequatur reiciendis rerum dolor. A sit et. Repudiandae ex aut. Ea et ad quis commodi ut tenetur est dolore.\n \rAdipisci magni et exercitationem unde quidem nam. Blanditiis explicabo fugit reprehenderit rerum. Beatae enim velit aperiam perspiciatis autem cumque cumque. Consectetur nesciunt sequi. Sequi suscipit odio excepturi rerum eius veritatis. Explicabo harum ducimus neque facere nam non et dolor.\n \rItaque odit architecto odit velit laborum et perspiciatis accusamus voluptas. Neque est et et natus quis est. Sed quia esse amet autem consectetur.'),
    ('Tigers', 1, 'Sequi in qui dolores perferendis pariatur neque eius. Qui et perspiciatis aliquam sit accusamus. Corporis qui dolores et minima non at numquam autem aut. Aut possimus minus facere dicta animi accusamus et sit quia.\n \rPerspiciatis sint itaque omnis nobis ipsam unde velit. Qui aut voluptatem quo magni similique. Quod qui maiores ex qui hic. Possimus cumque et corrupti. Dolor eaque et nihil. Error consequatur molestiae blanditiis aut quos non temporibus.\n \rAut expedita quaerat quod corporis eaque officia aspernatur. Ad ea ea incidunt voluptatem minus fuga. Quis molestiae hic ex vel. Nobis deleniti nulla qui nobis explicabo.'),
    ('Wolves', 2, 'Aspernatur voluptas eos sunt et cupiditate est est tempore. Ut tenetur dolorem quo aut nemo at ratione consequuntur. Repudiandae debitis distinctio fugiat. Non ex placeat rerum sapiente ipsum quas aut id consequatur.\n \rNobis veritatis voluptate odio. Natus quibusdam fugiat illum qui praesentium velit voluptate earum. Eos est tenetur qui velit autem nisi nihil modi ullam. Veritatis ea et consequatur consectetur asperiores odio quisquam quaerat et.\n \rEt iusto est. Et perferendis ut possimus vero natus. Assumenda a dolor qui saepe non repudiandae in neque. Optio et quae omnis dolores ea perspiciatis assumenda eaque.'),
    ('Elephants', 3, 'Ut molestiae sit quasi unde error ducimus. Est provident quasi laboriosam nesciunt. Voluptatum eligendi eaque dolorem non. Alias quis et tenetur eos. Ut sit consequatur.\n \rQuia consequatur deleniti nam facere aut non quia quisquam aut. Neque tenetur adipisci nostrum. Dolorem nostrum sit.\n \rDelectus in suscipit quis nostrum fuga fugiat itaque vel rem. Nisi eligendi rerum saepe corrupti. Mollitia inventore qui in delectus. Asperiores libero adipisci aut ratione facilis beatae. Soluta odit quaerat voluptatem. Ipsam tempore culpa vero et eaque dicta repellat enim commodi.'),
    ('Lions', 3, 'Amet expedita velit ut saepe eos enim perferendis rem. Aut quos illum. Vero et odit beatae et eos.\n \rQuis et illum rerum mollitia omnis vitae veniam. Molestiae aut facere voluptate officiis quam. Adipisci aliquam magni est voluptatem eius eos voluptas. Aut quod nostrum soluta eum.\n \rVelit qui soluta hic hic dolorem soluta reprehenderit vel. Fuga molestiae ea dolores impedit optio. Modi deleniti numquam voluptatum asperiores. Aut ab expedita tempora eligendi. Eos illum iste at expedita at et. Minus eveniet quis quia fuga accusantium et.'),
    ('Monkeys', 3, 'Sunt voluptatibus veritatis quam autem saepe laboriosam iste alias. Suscipit sequi natus iste quia facilis. Totam cum ut dolor sequi consequuntur.\n \rMinus eum vero quo placeat velit eum. Dolorum provident aut maxime ab sed. Et reprehenderit ab recusandae. Nulla placeat a molestiae qui id maxime. Fugiat in veniam et eum omnis. Error deleniti voluptatem ex.\n \rMagnam eligendi non aut hic eius quia dolor vero expedita. Vel omnis accusantium eius. Nemo animi blanditiis rerum totam tenetur eligendi quam voluptatibus. Sunt ullam corrupti ipsam iusto qui consequuntur est velit rerum. In assumenda dolorem facere mollitia sunt ex expedita labore consequatur. Repellat quae sed eaque facilis tenetur.'),
    ('Bats', 3, 'Ducimus quae unde aut ut aut minima error mollitia est. Architecto rerum ex possimus amet neque minus dolorem iusto esse. Inventore consequuntur asperiores non molestiae. At quia voluptatem eum occaecati quod. Ut omnis qui maxime. Placeat eaque et.\n \rSunt officiis accusantium ipsum in cumque quas earum ipsam. Nobis dignissimos corporis excepturi rerum. Non eius quas aliquid non omnis ab optio quidem dolor. Unde numquam doloremque voluptates et tenetur sit. Nulla et aperiam odio quae officiis ut hic dolorum.\n \rQuo et sed deleniti sed possimus ipsa inventore. Numquam est et perspiciatis aliquam et. Vel ipsam aut magni qui officia quasi voluptatem labore necessitatibus. Nobis quis alias maiores mollitia a quaerat hic repellat est.'),
    ('Turtles', 3, 'Minima veniam praesentium. Aut quia quas saepe aut. Accusamus et consequatur similique ea ut molestiae qui.\n \rId magnam et repudiandae architecto. Totam qui sint dolorem. Cupiditate minima accusantium aliquid.\n \rEt in voluptas corrupti enim magnam. Recusandae sequi facilis enim. Quo non saepe sit nam perferendis. Est culpa maxime rerum saepe impedit. Pariatur doloribus nobis vero. Quas et animi ut necessitatibus doloremque eum corrupti possimus velit.'),
    ('Zebras', 3, 'Est et ipsum vero a dolorem tempore qui et. Dolorum exercitationem molestiae odio ad rerum. Laudantium et voluptatibus eos. Quia enim sit cupiditate ab adipisci necessitatibus est aut voluptatibus. Quis fugit accusamus autem id nam.\n \rConsequuntur sint et ut eius eum. Et quas non corrupti eos ipsa. Repudiandae tempora rem porro. Temporibus ullam dolorem ex quo tempore libero aut natus in. Laborum in asperiores eos voluptatem nostrum.\n \rNisi eveniet libero. Autem ut sit similique ex voluptas. Quia aut iure aliquam error quis et aspernatur adipisci culpa.');